const CORTEZ_CONFIG={brand:"CORTÊS",subtitle:"Serviços Digitais",whatsappSites:"5579981719609",whatsappTraffic:"5579988133030",socialHandle:"@cortezweb.ia"};
function createWhatsAppURL(phone,message){return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`}
function openWhatsApp(type,message){const phone=type==="traffic"?CORTEZ_CONFIG.whatsappTraffic:CORTEZ_CONFIG.whatsappSites;const fallback=type==="traffic"?"Olá, Cortês. Gostaria de conversar sobre gestão de tráfego para meu negócio.":"Olá, Cortês. Gostaria de conversar sobre criação de sites e serviços digitais.";window.open(createWhatsAppURL(phone,message||fallback),"_blank","noopener,noreferrer")}
function initMenu(){const t=document.getElementById("menuToggle"),n=document.getElementById("mainNav");if(!t||!n)return;const c=()=>{t.classList.remove("is-open");n.classList.remove("is-open");t.setAttribute("aria-expanded","false")};t.addEventListener("click",()=>{const o=t.getAttribute("aria-expanded")!=="true";t.classList.toggle("is-open",o);n.classList.toggle("is-open",o);t.setAttribute("aria-expanded",String(o))});n.querySelectorAll("a").forEach(a=>a.addEventListener("click",c));window.addEventListener("resize",()=>{if(innerWidth>=980)c()})}
function initHeaderAndProgress(){const h=document.getElementById("siteHeader"),p=document.getElementById("progressBar");const u=()=>{if(h)h.classList.toggle("is-scrolled",scrollY>24);if(p){const m=document.documentElement.scrollHeight-innerHeight;p.style.width=`${m>0?Math.min(100,Math.max(0,scrollY/m*100)):0}%`}};u();addEventListener("scroll",u,{passive:true});addEventListener("resize",u)}
function initScrollAnimations(){const els=document.querySelectorAll(".reveal");if(!els.length)return;if(!("IntersectionObserver" in window)){els.forEach(e=>e.classList.add("is-visible"));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");o.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -7% 0px"});els.forEach(e=>o.observe(e))}
function initDigitalCut(){const c=document.getElementById("digitalCut"),ss=document.querySelectorAll(".cut-reveal,#servicos,#planos,#scan,#projetos,#sobre");if(!c||!ss.length||!("IntersectionObserver" in window))return;const seen=new WeakSet(),o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!seen.has(e.target)){seen.add(e.target);c.classList.remove("is-active");void c.offsetWidth;c.classList.add("is-active")}}),{threshold:.22});ss.forEach(s=>o.observe(s))}
function initWhatsApp(){document.querySelectorAll("[data-whatsapp]").forEach(b=>b.addEventListener("click",()=>openWhatsApp(b.dataset.whatsapp,b.dataset.message||"")))}
function initContactDock(){const t=document.getElementById("contactTrigger"),m=document.getElementById("contactMenu");if(!t||!m)return;const set=o=>{m.hidden=!o;t.setAttribute("aria-expanded",String(o))};t.addEventListener("click",()=>set(t.getAttribute("aria-expanded")!=="true"));document.querySelectorAll("[data-open-contact]").forEach(b=>b.addEventListener("click",()=>{set(true);t.focus({preventScroll:true})}));document.addEventListener("click",e=>{if(!e.target.closest("#contactDock")&&!e.target.closest("[data-open-contact]"))set(false)});document.addEventListener("keydown",e=>{if(e.key==="Escape")set(false)})}
function initFAQ(){document.querySelectorAll(".faq-item").forEach(i=>{const b=i.querySelector("button");if(!b)return;b.addEventListener("click",()=>{const o=!i.classList.contains("is-open");i.classList.toggle("is-open",o);b.setAttribute("aria-expanded",String(o))})})}
function getScanData(form){const d=new FormData(form);return{hasSite:d.get("hasSite")||"",ads:d.get("ads")||"",source:d.get("source")||"",problem:d.get("problem")||"",business:String(d.get("business")||"").trim()}}
function getScanRecommendation(d){if(d.hasSite==="Não"||d.problem==="Não tenho site"||d.problem==="Aparência pouco profissional")return{route:"sites",title:"Primeiro, fortaleça sua estrutura digital.",text:"Seu primeiro passo pode ser construir uma presença digital profissional antes de aumentar o tráfego. Uma estrutura clara ajuda o visitante a entender quem você é, o que oferece e qual deve ser a próxima ação."};if(d.problem==="Atendimento desorganizado")return{route:"sites",title:"O gargalo pode estar depois do interesse.",text:"Seu problema pode não ser falta de pessoas chegando, mas a maneira como elas são recebidas. Quiz, organização inicial e automações simples podem ajudar a tornar o atendimento mais estruturado."};if(d.problem==="Poucos clientes"||d.problem==="Anúncios não funcionam bem"||(d.hasSite==="Sim"&&d.ads==="Não"))return{route:"traffic",title:"Seu próximo gargalo pode estar na aquisição.",text:"Você já possui presença digital. O próximo passo pode ser avaliar como colocar sua empresa diante de mais pessoas com potencial de interesse, sem depender apenas de descoberta orgânica ou indicação."};return{route:"sites",title:"Organize sua presença antes do próximo investimento.",text:"Seu cenário indica que vale revisar a estrutura digital como um todo: apresentação, canais de entrada, clareza da oferta e forma de atendimento. A recomendação é orientativa e serve como ponto de partida."}}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function initCortezScan(){const f=document.getElementById("cortezScan"),n=document.getElementById("scanNext"),b=document.getElementById("scanBack"),l=document.getElementById("scanStepLabel"),p=document.getElementById("scanProgressFill"),r=document.getElementById("scanResult"),rt=document.getElementById("scanResultTitle"),rx=document.getElementById("scanResultText"),s=document.getElementById("scanSummary"),w=document.getElementById("scanWhatsApp"),rr=document.getElementById("scanRestart");if(!f||!n||!b||!l||!p||!r||!rt||!rx||!s||!w||!rr)return;const steps=[...f.querySelectorAll(".scan-step")];let c=1,rec=null;const update=()=>{steps.forEach(x=>x.classList.toggle("is-active",Number(x.dataset.step)===c));l.textContent=`ETAPA ${c} / 5`;p.style.width=`${c*20}%`;b.disabled=c===1;n.innerHTML=c===5?`Ver resultado <span>→</span>`:`Continuar <span>→</span>`};const valid=()=>{const a=f.querySelector(`.scan-step[data-step="${c}"]`);if(!a)return false;for(const x of a.querySelectorAll("[required]")){if(x.type==="radio"){const q=a.querySelector(`input[name="${x.name}"]:checked`);if(!q){x.focus();return false}}else if(!x.value.trim()){x.focus();return false}}return true};const show=()=>{const d=getScanData(f);rec=getScanRecommendation(d);rt.textContent=rec.title;rx.textContent=rec.text;s.innerHTML=`<div><strong>Site:</strong> ${esc(d.hasSite)}</div><div><strong>Anúncios:</strong> ${esc(d.ads)}</div><div><strong>Clientes vêm de:</strong> ${esc(d.source)}</div><div><strong>Maior dificuldade:</strong> ${esc(d.problem)}</div><div><strong>Negócio:</strong> ${esc(d.business)}</div>`;f.hidden=true;r.hidden=false;r.scrollIntoView({behavior:"smooth",block:"center"})};n.addEventListener("click",()=>{if(!valid())return;if(c<5){c++;update()}else show()});b.addEventListener("click",()=>{if(c>1){c--;update()}});w.addEventListener("click",()=>{const d=getScanData(f),q=rec||getScanRecommendation(d),sum=q.route==="traffic"?"avaliar aquisição e tráfego":"melhorar minha estrutura digital";openWhatsApp(q.route,`Olá, Cortês. Fiz o Cortês Scan no seu site.\n\nSite: ${d.hasSite}\nAnúncios: ${d.ads}\nClientes vêm de: ${d.source}\nMaior dificuldade: ${d.problem}\nNegócio: ${d.business}\n\nO Scan recomendou ${sum}.\n\nGostaria de conversar.`)});rr.addEventListener("click",()=>{f.reset();c=1;rec=null;r.hidden=true;f.hidden=false;update();f.scrollIntoView({behavior:"smooth",block:"center"})});update()}
function initMouseGlow(){const g=document.getElementById("mouseGlow");if(!g||!matchMedia("(hover: hover) and (pointer: fine)").matches)return;let tx=innerWidth/2,ty=innerHeight/2,cx=tx,cy=ty;addEventListener("mousemove",e=>{tx=e.clientX;ty=e.clientY},{passive:true});const a=()=>{cx+=(tx-cx)*.08;cy+=(ty-cy)*.08;g.style.left=`${cx}px`;g.style.top=`${cy}px`;requestAnimationFrame(a)};a()}
function initYear(){const y=document.getElementById("currentYear");if(y)y.textContent=new Date().getFullYear()}
document.addEventListener("DOMContentLoaded",()=>{initMenu();initHeaderAndProgress();initScrollAnimations();initDigitalCut();initWhatsApp();initContactDock();initFAQ();initCortezScan();initMouseGlow();initYear()});